studis/Models/IzpitniRok.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class izpitnirok
    {
        public izpitnirok()
        {
            this.prijavanaizpits = new HashSet<prijavanaizpit>();
        }
    
        public int id { get; set; }
        public System.DateTime datum { get; set; }
        public long izvajanjeId { get; set; }
        public Nullable<System.DateTime> ura { get; set; }
        public Nullable<int> prostorId { get; set; }
        public bool fiktiven { get; set; }
    
        public virtual sifrant_prostor sifrant_prostor { get; set; }
        public virtual ICollection<prijavanaizpit> prijavanaizpits { get; set; }
        public virtual izvajanje izvajanje { get; set; }
    }
}

studis/Controllers/IzpitniRokController.cs
using studis.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Data;
using System.Data.Entity;

namespace studis.Controllers
{
    [Authorize(Roles = "Profesor, Referent")]
    public class IzpitniRokController : Controller
    {
        public studisEntities db = new studisEntities();

        public ActionResult Index()
        {
            return View();
        }

        //GET: IzpitniRok/Dodaj
        public ActionResult Dodaj()
        {
            List<predmet> temp = db.predmets.OrderBy(a => a.ime).ToList();

            List<SelectListItem> predmeti = new List<SelectListItem>();
            foreach (predmet i in temp)
            {
                SelectListItem p = new SelectListItem();
                p.Value = i.id.ToString();
                p.Text = Convert.ToInt32(p.Value).ToString("000") + " - " + i.ime + " (" + i.koda + ")";
                predmeti.Add(p);
            }
            ViewBag.Predmets = new SelectList(predmeti, "Value", "Text");
            List<SelectListItem> ltemp = new List<SelectListItem>();
            ltemp.Add(new SelectListItem() { Value = "", Text = "Izbira izvajalcev" });
            ViewBag.Prazen = new SelectList(ltemp, "Value", "Text");
            //new SelectList(db.sifrant_studijskiprogram.OrderBy(a => a.naziv), "id", "naziv");
            //IzpitniRokModel model= new IzpitniRokModel();

            var uraSeznam = Enumerable.Range(0, 24).Select(i => new SelectListItem
               {
                   Value = i.ToString(),
                   Text = i.ToString("00")
               });
            var minuntaSeznam = Enumerable.Range(0, 60).Select(i => new SelectListItem
                {
                    Value = i.ToString(),
                    Text = i.ToString("00")
                });
            ViewBag.ura = uraSeznam;
            ViewBag.minuta = minuntaSeznam;

            var prostorSeznam = Enumerable.Range(1, 22).Select(i => new SelectListItem
            {
                Value = i.ToString(),
                Text = "P" + i.ToString("00")
            });

            ViewBag.prostor = prostorSeznam;

            return View();
        }

        // POST: IzpitniRok/Dodaj
        [HttpPost]
        public ActionResult Dodaj(IzpitniRokModel model)
        {
            izpitnirok izpitniRok = new izpitnirok();
            izpitniRok.datum = UserHelper.StringToDate(model.datum);
            izpitniRok.izvajanje = db.izvajanjes.SingleOrDefault(i => i.id == model.izvajanje);//db.predmets.SingleOrDefault(v => v.id == model.predmet);
            //izpitniRok.profesor = db.profesors.SingleOrDefault(p => p.id == model.profesor);
            if(model.ura != 0)
                izpitniRok.ura = UserHelper.IntsToTime(model.ura, model.minuta);
            if(model.prostor != 0)
                izpitniRok.prostorId = model.prostor;
            try
            {
                izpitniRok.fiktiven = false;
                // TODO: Add insert logic here
                db.izpitniroks.Add(izpitniRok);
                db.SaveChanges();
                return View("UspesnoDodan");
            }
            catch
            {
                return Dodaj();
            }
        }

        // GET: IzpitniRok/Edit
        public ActionResult Edit()
        {
            List<predmet> temp = db.predmets.OrderBy(a => a.ime).ToList();

            List<SelectListItem> predmeti = new List<SelectListItem>();
            foreach (predmet i in temp)
            {
                SelectListItem p = new SelectListItem();
                p.Value = i.id.ToString();
                p.Text = Convert.ToInt32(p.Value).ToString("000") + " - " + i.ime + " (" + i.koda + ")";
                predmeti.Add(p);
            }
            List<SelectListItem> ltemp = new List<SelectListItem>();
            ltemp.Add(new SelectListItem() { Value = "", Text = "Izbira" });
            ViewBag.Prazen = new SelectList(ltemp, "Value", "Text");
            ViewBag.Predmets = new SelectList(predmeti, "Value", "Text");

            var uraSeznam = Enumerable.Range(0, 24).Select(i => new SelectListItem
            {
                Value = i.ToString(),
                Text = i.ToString("00")
            });
            var minuntaSeznam = Enumerable.Range(0, 60).Select(i => new SelectListItem
            {
                Value = i.ToString(),
                Text = i.ToString("00")
            });
            ViewBag.ura = uraSeznam;
            ViewBag.minuta = minuntaSeznam;

            var prostorSeznam = Enumerable.Range(1, 22).Select(i => new SelectListItem
            {
                Value = i.ToString(),
                Text = "P" + i.ToString("00")
            });

            ViewBag.prostor = prostorSeznam;

            return View();
        }

        // POST: IzpitniRok/Edit
        [HttpPost]
        public ActionResult Edit(IzpitniRokModel model)
        {

            try
            {
                // TODO: Add update logic here
                var rok = db.izpitniroks.SingleOrDefault(r => r.id == model.id);

                rok.datum = UserHelper.StringToDate(model.datum);
                //rok.predmet = db.predmets.SingleOrDefault(v => v.id == model.predmet);
                if (model.ura != 0)
                {
                    rok.ura = UserHelper.IntsToTime(model.ura, model.minuta);
                }
                else
                {
                    rok.ura = null;
                }
                if (model.prostor != 0)
                {
                    rok.prostorId = model.prostor;
                }
                else
                {
                    rok.prostorId = null;
                }
                Debug.WriteLine("Prostor " + model.prostor);
                db.SaveChanges();
                return View("UspesnoSpremenjen");
            }
            catch
            {
                return Edit();
            }
        }

        // GET: IzpitniRok/Delete/5
        public ActionResult Izbrisi()
        {
            List<predmet> temp = db.predmets.OrderBy(a => a.ime).ToList();

            List<SelectListItem> predmeti = new List<SelectListItem>();
            foreach (predmet i in temp)
            {
                SelectListItem p = new SelectListItem();
                p.Value = i.id.ToString();
                p.Text = Convert.ToInt32(p.Value).ToString("000") + " - " + i.ime + " (" + i.koda + ")";
                predmeti.Add(p);
            }
            List<SelectListItem> ltemp = new List<SelectListItem>();
            ltemp.Add(new SelectListItem() { Value = "", Text = "Izbira" });
            ViewBag.Prazen = new SelectList(ltemp, "Value", "Text");
            ViewBag.Predmets = new SelectList(predmeti, "Value", "Text");
            return View();
        }

        // POST: IzpitniRok/Delete/5
        [HttpPost]
        public ActionResult Izbrisi(int id)
        {
            try
            {
                // TODO: Add delete logic here
                db.izpitniroks.Remove(db.izpitniroks.SingleOrDefault(r => r.id == id));
                db.SaveChanges();
                return View("UspesnoIzbrisan");
            }
            catch
            {
                return Izbrisi();
            }
        }

        // GET: IzpitniRok/Seznam/5
        public ActionResult Seznam()
        {
            List<SelectListItem> predmeti = new List<SelectListItem>();

            if (User.IsInRole("Referent"))
            {
                List<predmet> temp = db.predmets.OrderBy(a => a.ime).ToList();
                foreach (predmet i in temp)
                {
                    SelectListItem p = new SelectListItem();
                    p.Value = i.id.ToString();
                    p.Text = Convert.ToInt32(p.Value).ToString("000") + " - " + i.ime + " (" + i.koda + ")";
                    predmeti.Add(p);
                }
            }
            else if (User.IsInRole("Profesor"))
            {
                int profid = Convert.ToInt32(UserHelper.getProfByName(User.Identity.Name).id);
                var izvajanja = db.izvajanjes.Where(a => a.izvajalec1Id == profid || a.izvajalec2Id == profid || a.izvajalec3Id == profid);
                if (izvajanja != null)
                {
                    foreach (izvajanje i in izvajanja.ToList())
                    {
                        SelectListItem p = new SelectListItem();
                        p.Value = i.predmetId.ToString();
                        p.Text = Convert.ToInt32(p.Value).ToString("000") + " - " + i.predmet.ime + " (" + i.predmet.koda + ")";
                        predmeti.Add(p);
                    }
                }
            }


            List<SelectListItem> ltemp = new List<SelectListItem>();
            ltemp.Add(new SelectListItem() { Value = "", Text = "Iščem.." });
            ViewBag.Prazen = new SelectList(ltemp, "Value", "Text");
            ViewBag.Predmets = new SelectList(predmeti, "Value", "Text");
            return View();
        }

        // POST: IzpitniRok/Seznam/5
        [HttpPost]
        public ActionResult Seznam(int id = -1)
        {
            try
            {
                izpitnirok rok = db.izpitniroks.Where(i => i.id == id).SingleOrDefault();

                return RedirectToAction("SeznamPrijavljenihKandidatov", rok);
            }
            catch
            {
                return Seznam();
            }
        }

        public ActionResult SeznamPrijavljenihKandidatov(izpitnirok rok)
        {
            if(rok == null)
                return RedirectToAction("Seznam");

            //podatki o izpitnem roku
            sifrant_prostor predavalnica = db.sifrant_prostor.Where(s => s.id == rok.prostorId).SingleOrDefault();
            izvajanje izv = db.izvajanjes.Where(s => s.id == rok.izvajanjeId).SingleOrDefault();

studis/Views/IzpitniRok/Index.cshtml
@{
    ViewBag.Title = "Izpitni roki";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upravljanje izpitnih rokov</h2>

<ul>
    
    @if (User.IsInRole("Referent"))
    {
        <li>@Html.ActionLink("Dodaj", "Dodaj", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent"))
    {
        <li>@Html.ActionLink("Spremeni", "Edit", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent") || User.IsInRole("Profesor"))
    {
        <li>@Html.ActionLink("Izbriši", "Izbrisi", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent") || User.IsInRole("Profesor"))
    {
    <li>@Html.ActionLink("Seznam prijavljenih kandidatov", "Seznam", "IzpitniRok")</li>
    }
</ul>

studis/Views/IzpitniRok/IndiVpisOcen.cshtml
@model IList<studis.Models.VnosTockModel>
    @{
        ViewBag.Title = "Individualni vpis ocen";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>

    <h2>Individualni vpis ocen</h2>

    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <table id="izpis" class="table">
            <tr>
                <th>Šifra predmeta</th>
                <th>Ime predmeta</th>
                <th>Izpraševalci</th>
                <th>Datum izvajanja</th>
                <th>Ura izvajanja</th>
                <th>Prostor</th>
            </tr>
            <tr>
                <td>@ViewBag.sifraPredmeta</td>
                <td>@ViewBag.imePredmeta</td>
                <td>@ViewBag.izvajalci</td>
                <td>@ViewBag.datum</td>
                <td>@ViewBag.ura</td>
                <td>@ViewBag.prostor</td>
            </tr>
            <tr>
                <th>
                    Zaporedna številka
                </th>
                <th>
                    Vpisna številka
                </th>
                <th>
                    Priimek
                </th>
                <th>
                    Ime
                </th>
                <th>
                    Študijsko leto
                </th>
                <th>
                    Zap. št. polaganja
                </th>
                <th>
                    Ocena
                </th>
                <th>
                    Vpiši/spremeni oceno
                </th>
            </tr>
            @if (Model != null)
            {
                for (var i = 0; i < Model.Count; i++)
                {
                    @Html.HiddenFor(x => x[i].idRoka)
                    <tr>
                        <td>
                            @Html.DisplayFor(x => x[i].zaporednaStevilka)
                            @Html.HiddenFor(x => x[i].zaporednaStevilka)
                        </td>
                        <td>
                            @Html.DisplayFor(x => x[i].vpisnaStevilka)
                            @Html.HiddenFor(x => x[i].vpisnaStevilka)
                        </td>
                        <td>
                            @Html.DisplayFor(x => x[i].priimek)
                            @Html.HiddenFor(x => x[i].priimek)
                        </td>
                        <td>
                            @Html.DisplayFor(x => x[i].ime)
                            @Html.HiddenFor(x => x[i].ime)
                        </td>
                        <td>
                            @Html.DisplayFor(x => x[i].studijskoLeto)
                            @Html.HiddenFor(x => x[i].studijskoLeto)
                        </td>
                        <td>
                            @Html.DisplayFor(x => x[i].zaporednoSteviloPonavljanja)
                            @Html.HiddenFor(x => x[i].zaporednoSteviloPonavljanja)
                        </td>
                        <td>
                            @Html.DisplayFor(x => x[i].zeVpisanaOcena)
                            @Html.HiddenFor(x => x[i].zeVpisanaOcena)
                        </td>
                        <td class="editor-field">
                            @Html.TextBoxFor(x => x[i].ocena)
                            @Html.ValidationMessageFor(x => x[i].ocena)
                        </td>
                    </tr>
                }
            }
        </table>
        <p>
            <input id="submit" type="submit" value="Potrdi vnos">
        </p>
    }
    @if (User.IsInRole("Referent") || User.IsInRole("Profesor"))
    {
        <li>@Html.ActionLink("Izpiši seznam s končnimi ocenami", "IzpisOcen", "IzpitniRok", new { rokID = @ViewBag.idRoka, seznam = 0 }, null)</li>
        <li>@Html.ActionLink("Izpiši seznam s končnimi ocenami(brez imen)", "IzpisOcen", "IzpitniRok", new { rokID = @ViewBag.idRoka, seznam = 1 }, null)</li>
    }

studis/Views/IzpitniRok/IzpisOcen.cshtml
@model IList<studis.Models.VnosTockModel>
    @{
        ViewBag.Title = "Izpis ocen";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>Izpis seznama s končnimi ocenami</h2>


    <table id="izpis" class="table">
        <tr>
            <th>Šifra predmeta</th>
            <th>Ime predmeta</th>
            <th>Izpraševalci</th>
            <th>Datum izvajanja</th>
            <th>Ura izvajanja</th>
            <th>Prostor</th>
        </tr>
        <tr>
            <td>@ViewBag.sifraPredmeta</td>
            <td>@ViewBag.imePredmeta</td>
            <td>@ViewBag.izvajalci</td>
            <td>@ViewBag.datum</td>
            <td>@ViewBag.ura</td>
            <td>@ViewBag.prostor</td>
        </tr>
        <tr>
            <th>
                Zaporedna številka
            </th>
            <th>
                Vpisna številka
            </th>
            <th>
                Priimek
            </th>
            <th>
                Ime
            </th>
            <th>
                Študijsko leto
            </th>
            <th>
                Zap. št. polaganja
            </th>
            <th>
                Točke
            </th>
            <th>
                Ocena
            </th>

        </tr>
        @if (Model != null)
        {
            for (var i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => x[i].zaporednaStevilka)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].vpisnaStevilka)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].priimek)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].ime)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].studijskoLeto)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].zaporednoSteviloPonavljanja)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].zeVpisaneTocke)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].zeVpisanaOcena)
                    </td>
                </tr>
            }
        }
    </table>

studis/Views/IzpitniRok/Izvajanja.cshtml
@using studis.Models

@{
    ViewBag.Title = "Izbira izvajanja za vpis ocene";
    Layout = "~/Views/Shared/_Layout.cshtml";
    StudentHelper sh = new StudentHelper();
    int v = 0;
    vpi v2 = null;
    int polaganja = 0;
    int zocena = -1;
}

<h2>Izbira izvajanja za vpis ocene</h2>

<br />

<h3>@ViewBag.Vpis.vpisnaStevilka - @ViewBag.Vpis.student.ime @ViewBag.Vpis.student.priimek</h3>

@if (@ViewBag.Izvajanja.Count == 0)
{
    <br />
    if (User.IsInRole("Referent"))
    {
        <h4 style="color: red;">Študent nima izvajanj za tekoče šolsko leto.</h4>
    }
    else if (User.IsInRole("Profesor"))
    {
        <h4 style="color: red;">Študent pri vas nima izvajanj za tekoče šolsko leto.</h4>
    }

}
else
{
    <table>
        <thead>
            <tr>
                <th>Šifra</th>
                <th>Predmet</th>
                <th>Letnik</th>
                <th>Študijski program</th>
                <th>Izvajalci</th>
                <th>Polaganja</th>
                <th>Zadnja ocena</th>
                <th>Dodaj oceno</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var i in @ViewBag.Izvajanja)
            {
                if (@ViewBag.Ponavljanje == null)
                {
                    { 
                     v = sh.pridobiVpisIzIzvajanja(Convert.ToInt32(i.id), Convert.ToInt32(ViewBag.Vpis.vpisnaStevilka));
                     v2 = sh.pridobiVpisIzIzvajanjaObj(Convert.ToInt32(i.id), Convert.ToInt32(ViewBag.Vpis.vpisnaStevilka));
                     polaganja = sh.polaganjaVsa(Convert.ToInt32(ViewBag.Vpis.vpisnaStevilka), Convert.ToInt32(i.id), Convert.ToInt32(v2.studijskiProgram));
                     zocena = sh.zadnjaOcena(Convert.ToInt32(ViewBag.Vpis.vpisnaStevilka), Convert.ToInt32(i.id)); 
                    }
                    <tr>
                        <td>@i.predmet.koda</td>
                        <td>@i.predmet.ime</td>
                        <td>@i.predmet.letnik</td>
                        <td>@i.predmet.sifrant_studijskiprogram.naziv</td>
                        <td>
                            @i.profesor.ime @i.profesor.priimek
                            @if (@i.izvajalec2Id != null)
                            {
                                <span>, <br />@i.profesor1.ime @i.profesor1.priimek</span>
                            }
                            @if (@i.izvajalec3Id != null)
                            {
                                <span>, <br />@i.profesor2.ime @i.profesor2.priimek</span>
                            }
                        </td>
                        <td>
                            @polaganja
                        </td>
                        <td>
                            @if (zocena == -1)
                            {
                                <span>/</span>
                            }
                            else
                            {
                                @zocena
                            }
                        </td>
                        <td>@Html.ActionLink("Dodaj", "VnosOcenBrezPrijave", "IzpitniRok", new { izvajanjeId = @i.id, vpisId = @v }, null)</td>
                    </tr>
                }
                else
                {
                    {
                        polaganja = sh.polaganjaLetos(Convert.ToInt32(ViewBag.Ponavljanje.id), Convert.ToInt32(i.id)); ;
                        zocena = sh.zadnjaOcena(Convert.ToInt32(ViewBag.Vpis.vpisnaStevilka), Convert.ToInt32(i.id));
                    }
                    <tr>
                        <td>@i.predmet.koda</td>
                        <td>@i.predmet.ime</td>
                        <td>@i.predmet.letnik</td>
                        <td>@i.predmet.sifrant_studijskiprogram.naziv</td>
                        <td>
                            @i.profesor.ime @i.profesor.priimek
                            @if (@i.izvajalec2Id != null)
                            {
                                <span>, <br />@i.profesor1.ime @i.profesor1.priimek</span>
                            }
                            @if (@i.izvajalec3Id != null)
                            {
                                <span>, <br />@i.profesor2.ime @i.profesor2.priimek</span>
                            }
                        </td>
                        <td>
                            @polaganja
                        </td>
                        <td>
                            @if (zocena == -1)
                            {
                                <span>/</span>
                            }
                            else
                            {
                                @zocena
                            }
                        </td>
                        <td>@Html.ActionLink("Dodaj", "VnosOcenBrezPrijave", "IzpitniRok", new { izvajanjeId = @i.id, vpisId = @ViewBag.Ponavljanje.id }, null)</td>
                    </tr>
                }
            }
        </tbody>
    </table>
}

studis/Views/IzpitniRok/SeznamPrijavljenihKandidatov.cshtml
@model IEnumerable<studis.Models.VnosTockModel>
@using studis.Models

@{
    ViewBag.Title = "SeznamPrijavljenihKandidatov";
    Layout = "~/Views/Shared/_Layout.cshtml";
    StudentHelper sh = new StudentHelper();
}

<h2>Seznam prijavljenih kandidatov za izbrani izpitni rok</h2>

<table id="izpis" class="table">
    <tr>
        <th>Šifra predmeta</th>
        <th>Ime predmeta</th>
        <th>Izpraševalci</th>
        <th>Datum izvajanja</th>
        <th>Ura izvajanja</th>
        <th>Prostor</th>
    </tr>
    <tr>
        <td>@ViewBag.sifraPredmeta</td>
        <td>@ViewBag.imePredmeta</td>
        <td>@ViewBag.izvajalci</td>
        <td>@ViewBag.datum</td>
        <td>@ViewBag.ura</td>
        <td>@ViewBag.prostor</td>
    </tr>
    <tr>
        <th>
            Zaporedna številka
        </th>
        <th>
            Vpisna številka
        </th>
        <th>
            Priimek
        </th>
        <th>
            Ime
        </th>
        <th>
            Študijsko leto
        </th>
        <th>
            Zap. št. polaganja
        </th>
        <th>
            Vpis ocene
        </th>
    </tr>
@if(Model!=null)
{
    foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.zaporednaStevilka)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vpisnaStevilka)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.priimek)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.studijskoLeto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.zaporednoSteviloPonavljanja)
        </td>
        @if (ViewBag.ocenetocke == true)
        {
        <td>
            @{ var prijavaId = sh.pridobiPrijavaId(Convert.ToInt32(item.vpisnaStevilka), @ViewBag.idRoka); }
            @Html.ActionLink("Vpis", "IndiVpisOcen", "IzpitniRok", new { rokId = @ViewBag.idRoka, prijavaID = @prijavaId }, null)
        </td>
        }
        else
        {
            <td>Ni mogoče</td>
        }
    </tr>
    }
}
</table><br/>
@if (User.IsInRole("Referent") || User.IsInRole("Profesor"))
{ 
    if (ViewBag.ocenetocke == true)
    {
        <li>@Html.ActionLink("Vpiši točke", "VpisTock", "IzpitniRok", new { rokID = @ViewBag.idRoka }, null)</li>
        <li>@Html.ActionLink("Vpiši ocene", "VpisOcen", "IzpitniRok", new { rokID = @ViewBag.idRoka }, null)</li>
    }
    <li>@Html.ActionLink("Izpiši seznam s točkami", "IzpisTock", "IzpitniRok", new { rokID = @ViewBag.idRoka, seznam = 0 }, null)</li>
    <li>@Html.ActionLink("Izpiši seznam s točkami(brez imen)", "IzpisTock", "IzpitniRok", new { rokID = @ViewBag.idRoka, seznam = 1 }, null)</li>
    <li>@Html.ActionLink("Izpiši seznam s končnimi ocenami", "IzpisOcen", "IzpitniRok", new { rokID = @ViewBag.idRoka, seznam = 0 }, null)</li>
    <li>@Html.ActionLink("Izpiši seznam s končnimi ocenami(brez imen)", "IzpisOcen", "IzpitniRok", new { rokID = @ViewBag.idRoka, seznam = 1 }, null)</li>
}

studis/Views/IzpitniRok/UspesnoDodan.cshtml
@{
    ViewBag.Title = "UspesnoDodan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Izpitni rok je bil uspešno dodan</h2>

<ul>

    @if (User.IsInRole("Referent"))
    {
        <li>@Html.ActionLink("Dodaj", "Dodaj", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent"))
    {
        <li>@Html.ActionLink("Spremeni", "Edit", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent") || User.IsInRole("Profesor"))
    {
        <li>@Html.ActionLink("Izbriši", "Izbrisi", "IzpitniRok")</li>
    }

</ul>

studis/Views/IzpitniRok/UspesnoIzbrisan.cshtml
@{
    ViewBag.Title = "UspesnoIzbrisan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Izpitni rok je bil uspešno izbrisan</h2>

<ul>

    @if (User.IsInRole("Referent"))
    {
        <li>@Html.ActionLink("Dodaj", "Dodaj", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent"))
    {
        <li>@Html.ActionLink("Spremeni", "Edit", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent") || User.IsInRole("Profesor"))
    {
        <li>@Html.ActionLink("Izbriši", "Izbrisi", "IzpitniRok")</li>
    }

</ul>

studis/Views/IzpitniRok/UspesnoSpremenjen.cshtml
@{
    ViewBag.Title = "UspesnoSpremenjen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Izpitni rok je bil uspešno spremenjen</h2>

<ul>

    @if (User.IsInRole("Referent"))
    {
        <li>@Html.ActionLink("Dodaj", "Dodaj", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent"))
    {
        <li>@Html.ActionLink("Spremeni", "Edit", "IzpitniRok")</li>
    }
    @if (User.IsInRole("Referent") || User.IsInRole("Profesor"))
    {
        <li>@Html.ActionLink("Izbriši", "Izbrisi", "IzpitniRok")</li>
    }

</ul>